// This file is auto-generated by scripts/ingestCurriculum.ts. Do not edit manually.
import { Question } from "./levelsEngine";

export interface CurriculumChapter {
  id: number;
  ncertClass: number;
  chapterNumber: number;
  name: string;
  tier: "beginner" | "professional" | "expert";
  questions: Question[];
}

export const curriculumChapters: CurriculumChapter[] = [
  {
    "id": 1,
    "ncertClass": 6,
    "chapterNumber": 1,
    "name": "Class 6 Chapter 1: Vowels and Basic Sandhi",
    "tier": "beginner",
    "questions": [
      {
        "id": "ingested-class6-ch1-1",
        "phrase": "देवालयः",
        "transliterations": {
          "devanagari": "देवालयः",
          "iast": "devālayaḥ",
          "japanese": "サンスクリット発音",
          "french": "devālayaḥ"
        },
        "wordByWord": [
          {
            "sanskrit": "देवालयः",
            "english": "devālayaḥ",
            "role": "Sanskrit Stem"
          }
        ],
        "grammaticalRule": "Akaḥ Savarṇe Dīrghaḥ (Vowels a/i/u/ṛ meeting a similar vowel become long) (Ashtadhyayi 6.1.101)",
        "sourceAttribution": "Panini Ashtadhyayi 6.1.101 / NCERT Class 6 Chapter 3",
        "options": [
          "Deva + Ālayaḥ (Dīrgha Sandhi)",
          "Deva + Layaḥ (Guṇa Sandhi)",
          "Dev + Ālayaḥ (Vṛddhi Sandhi)",
          "Deva + Alayaḥ (Yaṇ Sandhi)"
        ],
        "correctIndex": 0,
        "hint": "Observe the junction point: the 'a' at the end of 'Deva' and the 'ā' at the start of 'ālayaḥ' fuse into a long 'ā' (Devālayaḥ).",
        "conceptType": "Sandhi & Word-Junctions",
        "paninianHeritage": "Akaḥ Savarṇe Dīrghaḥ (Vowels a/i/u/ṛ meeting a similar vowel become long) (6.1.101)",
        "sourceAttributionTelemetry": "Panini Ashtadhyayi 6.1.101 / NCERT Class 6 Chapter 3",
        "pronunciationAcoustics": {
          "akshara": "d-e-v-ā-l-a-y-a-ḥ",
          "matra": "1-1-1",
          "uchcharana": "Sanskrit Acoustics"
        }
      },
      {
        "id": "ingested-class6-ch1-2",
        "phrase": "इत्येवम्",
        "transliterations": {
          "devanagari": "इत्येवम्",
          "iast": "ityevam",
          "japanese": "サンスクリット発音",
          "french": "ityevam"
        },
        "wordByWord": [
          {
            "sanskrit": "इत्येवम्",
            "english": "ityevam",
            "role": "Sanskrit Stem"
          }
        ],
        "grammaticalRule": "Iko Yaṇaci (i/u/ṛ/ḷ + dissimilar vowel = y/v/r/l + vowel) (Ashtadhyayi 6.1.77)",
        "sourceAttribution": "Panini Ashtadhyayi 6.1.77 / NCERT Class 7 Chapter 4",
        "options": [
          "Iti + Evam (Yaṇ Sandhi)",
          "Ite + Vam (Dīrgha Sandhi)",
          "It + Evam (Guṇa Sandhi)",
          "Iti + Aivam (Vṛddhi Sandhi)"
        ],
        "correctIndex": 0,
        "hint": "The ending short 'i' in 'iti' undergoes transition into the semi-vowel 'y' when followed by the dissimilar vowel 'e' in 'evam'.",
        "conceptType": "Sandhi & Word-Junctions",
        "paninianHeritage": "Iko Yaṇaci (i/u/ṛ/ḷ + dissimilar vowel = y/v/r/l + vowel) (6.1.77)",
        "sourceAttributionTelemetry": "Panini Ashtadhyayi 6.1.77 / NCERT Class 7 Chapter 4",
        "pronunciationAcoustics": {
          "akshara": "i-t-y-e-v-a-m",
          "matra": "1-1-1",
          "uchcharana": "Sanskrit Acoustics"
        }
      }
    ]
  },
  {
    "id": 2,
    "ncertClass": 7,
    "chapterNumber": 1,
    "name": "Class 7 Chapter 1: Guna Sandhi & Vyakaran Basics",
    "tier": "beginner",
    "questions": [
      {
        "id": "ingested-class7-ch1-1",
        "phrase": "महोत्सवः",
        "transliterations": {
          "devanagari": "महोत्सवः",
          "iast": "mahotsavaḥ",
          "japanese": "サンスクリット発音",
          "french": "mahotsavaḥ"
        },
        "wordByWord": [
          {
            "sanskrit": "महोत्सवः",
            "english": "mahotsavaḥ",
            "role": "Sanskrit Stem"
          }
        ],
        "grammaticalRule": "Ād Guṇaḥ (ā + u becomes o) (Ashtadhyayi 6.1.87)",
        "sourceAttribution": "Panini Ashtadhyayi 6.1.87 / NCERT Class 7 Chapter 4",
        "options": [
          "Mahā + Utsavaḥ (Guṇa)",
          "Maho + Tsavaḥ (Dīrgha)",
          "Mahā + Tsavaḥ (Vṛddhi)",
          "Maha + Utsavaḥ (Yan)"
        ],
        "correctIndex": 0,
        "hint": "The ending vowel 'ā' in 'Mahā' meets the starting vowel 'u' in 'Utsavaḥ' to form the Guṇa vowel 'o'.",
        "conceptType": "Sandhi & Word-Junctions",
        "paninianHeritage": "Ād Guṇaḥ (ā + u becomes o) (6.1.87)",
        "sourceAttributionTelemetry": "Panini Ashtadhyayi 6.1.87 / NCERT Class 7 Chapter 4",
        "pronunciationAcoustics": {
          "akshara": "m-a-h-o-t-s-a-v-a-ḥ",
          "matra": "1-1-1",
          "uchcharana": "Sanskrit Acoustics"
        }
      }
    ]
  }
];
